version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: rentmatch
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot-app:
    build: .
    expose:
      - "8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_DURATION: ${JWT_DURATION}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rentmatch
      SPRING_DATASOURCE_USERNAME: springstudent
      SPRING_DATASOURCE_PASSWORD: springstudent
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - springboot-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mysql-data: